- name: add elastic deb
  shell: |
   curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch |sudo gpg --dearmor -o /usr/share/keyrings/elastic.gpg
   echo "deb [signed-by=/usr/share/keyrings/elastic.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
   wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  become: true

- name: update & upgrade
  ansible.builtin.apt:
    upgrade: yes
    update_cache: 'true'
  become: true

- name: install packages
  ansible.builtin.apt:
      pkg:
      - openjdk-11-jre-headless
      - apt-transport-https
      - logstash
      # - elasticsearch
      # - unzip
      # - nginx
  become: true

