- name: update & upgrade
  ansible.builtin.apt:
    upgrade: yes
    update_cache: 'true'
  become: true
  
- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - apache2 
    - ghostscript 
    - libapache2-mod-php 
    - mysql-client 
    - php 
    - php-bcmath 
    - php-curl 
    - php-imagick 
    - php-intl 
    - php-json 
    - php-mbstring 
    - php-mysql 
    - php-xml 
    - php-zip
  become: true